# Generated by Django 4.2.1 on 2023-10-01 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('Notification_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Notification_Text', models.TextField()),
                ('Notification_Date', models.DateTimeField(auto_now_add=True)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registeredusers')),
            ],
        ),
    ]
